### ISSUE TITLE
Inject assembly attributes on compilation as well as git

### ISSUE THREAD

**Issue by roji** [damageboy/daemaged.gitinfoplanter#3]
How about also injecting attributes with:
- Which user compiled
- On which machine
- In which directory

etc.

The injection of these attributes could be optional...

**Comment by roji** [comment]
You're doing conditional injection of these for .NET 4.5 only, which is good, but you require users to pass --platform in order to know which .NET we're on. Deduce this from the DLL you're injecting instead...

**Comment by damageboy** [comment]
Good idea, I'll get to it.

**Comment by roji** [comment]
Here's a way to detect .NET 4.5 on a DLL:

[assembly: TargetFramework(".NETFramework,Version=v4.5", FrameworkDisplayName = ".NET Framework 4.5")]

**Comment by damageboy** [comment]
I'm splitting the platform detection to another Issue
